### ISSUE TITLE
Can't install caffe

### ISSUE THREAD

**Issue by monokuma-zhuo** [yizhouDu/installation_caffe_colab#1]
I follow your steps. Every step is successful in colab. But in step 6 "Verify if Caffe works“，it occurs error that "No module named 'caffe'".

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-14-734924e52be1>](https://localhost:8080/#) in <module>()
      1 import cv2
----> 2 import caffe

ModuleNotFoundError: No module named 'caffe'

How can I solve this problem? Thanks for reply!

**Comment by durinn88** [comment]
Hi Zhuo, I've checked the code and ensured they still work for me. Here I try to provide several suggestions for you to make your installation successful:

1. Check whether all code where modified folder path is replaced to yours. I believe they are:

- [ ] Drive mount folder path in _Step 2. Mount to your Google Drive_
- [ ] The  _!export_ sentences and _!chmod_ sentences in inbox9 in _Step 5. Make necessary Adjustments_
- [ ] The _sys.path.insert_ sentences in inbox16 in _Step 5. Make necessary Adjustments_


2. If the error _"ModuleNotFoundError: No module named 'caffe'"_ still occurs, run the cell inbox15 to clean up all makefile outputs and then rerun the cell inbox16 to make again.

3. If none of the above works, replace the cell inbox31 in _Step6. Verify if Caffe works_ with the code segment below instead:

`%cd ..`
`import cv2`
`import caffe`
`%cd caffe`


Hope the suggestions work for you. If not, please let me know and I'll think of further solutions.
